### ISSUE TITLE
Automatic install for Recalbox(wrong installation script)

### ISSUE THREAD

**Issue by idontknowthings** [Vegz78/McAirpos#26] opened 2021-12-16 23:12 UTC
My raspberry pi with retro pi installed is saying something along the lines of permission denied, I don't know how to explain it so here's what I got through SSH.

![image](https://user-images.githubusercontent.com/96268848/146462365-a0d0ece5-70f0-4c0d-b34a-898f4069ff94.png)

Also, can anyone make a tutorial to install Mcairpos and how to get games working?

Thanks

**Comment by Vegz78** [comment] 2021-12-17 08:57
Hi @idontknowthings,

Thanks for trying McAirpos!

I am a little confused here, since in this issue's header, you mention Recalbox, while you introduce your issue by explaining that you have a "...raspberry pi with RetroPie installed...". The latter seems to be confirmed by your command prompt showing "pi@retropie", where the _pi_ user does not exist on Recalbox installations.

Given that you are on Raspberry Pi OS/RetroPie, and not on Recalbox, there is a similar automatic installation script you can use for RetroPie here:
https://github.com/Vegz78/McAirpos#quick-automatic-installation-for-retropierpi-os

Please report back how this works or does not work for you.

> Also, can anyone make a tutorial to install Mcairpos and how to get games working?

IMHO, I believe there is ample information in the readme.md on the main repo page about how to install, use and configure McAirpos with controller support. So, the instructions might always be improved upon, and if you believe something is missing, please be more specific about what you find is missing or help me fill in the blanks:
https://github.com/Vegz78/McAirpos

**Comment by Vegz78** [comment] 2021-12-21 23:14
Closing this issue since I have not heard anymore back from @idontknowthings. I hope that the RetroPie install script still works, and that this issue was solved with many new retro-like MakeCode Arcade games now being made and played in yet another RetroPie installation!

**Closed as completed by Vegz78** 2021-12-21 23:14 UTC
Labels: help wanted
