### ISSUE TITLE
Controllers setups

### ISSUE THREAD

**Issue by claricerogue** [Vegz78/McAirpos#8] opened 2021-03-23 20:09 UTC
I don't have so much experience with retropie and controller config so sorry if it's a basic config problem.
I have two usb homemade  arcade controllers. Both work with emulation station and arcade games but when i run a makecode game, unless it works during the game, I can't exit with the start-hotkey buttons, I have to use the keyboard ctrl/ and then both gamepads  miss the configuration for all retropie, and I have to reset the machine. If I only reset emulastation, it shows the makecode's last game screen, as if it continue running but controllers or keyboard doesn't work any more. 
When I reset, pads get the correct config again.
Do I have to config the controllers by command line? If so, the mcairpos controller config affects the retropi controller config?

**Comment by Vegz78** [comment] 2021-03-23 20:14
Duplicate of https://github.com/Vegz78/McAirpos/issues/9

**Closed by Vegz78** 2021-03-23 20:14 UTC
