### ISSUE TITLE
link generation broken?(Solved as still working)

### ISSUE THREAD

**Issue by CrispStrobe** [Vegz78/McAirpos#61] opened 2024-07-14 19:54 UTC
i seemingly cannot generate ELFs anymore per those URL tricks. but it works still in makecode arcade beta per choosing rpi0 as hardware and downloading the file.

**Comment by Vegz78** [comment] 2024-10-09 08:26
Hi @CrispStrobe,

I just tested and am unable to replicate your experience. Links for downloading .elf files directly by just pushing the download button in the MakeCode editor are produced just fine when tested on newest Chrome browser on Windows and an older Opera browser on MacOS.

Link used: https://arcade.makecode.com/82170-98485-81323-67083
Link generated in browsers from [the McAirpos github.io site](https://vegz78.github.io/McAirpos/):
https://arcade.makecode.com/?nolocalhost=1&compile=rawELF&hw=rpi#editor

Could you please be a little more specific, for example provide me with the game share link you were trying to convert, info about your browser etc.?

**Comment by Vegz78** [comment] 2024-10-13 21:14
Closing this, since I cannot reproduce and it works as far as I can tell.

Please reopen if still a problem.

**Closed as completed by Vegz78** 2024-10-13 21:14 UTC
Labels: help wanted
